-- File generated by the BNF Converter (bnfc 2.9.5).
{-# LANGUAGE CPP #-}
{-# LANGUAGE FlexibleInstances #-}
---------------------------------------------------------------------------
-- Pattern synonyms exist since ghc 7.8.
{-# LANGUAGE PatternSynonyms #-}
{-# OPTIONS_GHC -Wno-orphans #-}

{- | BNF Converter: Error Monad.

 Module for backwards compatibility.

 The generated parser now uses @'Either' String@ as error monad.
 This module defines a type synonym 'Err' and pattern synonyms
 'Bad' and 'Ok' for 'Left' and 'Right'.
-}
module Latte.Grammar.ErrM where

import Prelude (Either (..), String, const, id)

import Control.Applicative (Alternative (..))
import Control.Monad (MonadFail (..), MonadPlus (..))

-- | Error monad with 'String' error messages.
type Err = Either String

pattern Bad :: String -> Err a
pattern Bad msg = Left msg
pattern Ok :: b -> Err b
pattern Ok x = Right x

instance MonadFail Err where
    fail = Bad

instance Alternative Err where
    empty = Left "Err.empty"
    (<|>) Left{} = id
    (<|>) x@Right{} = const x

instance MonadPlus Err where
    mzero = empty
    mplus = (<|>)
